name: Terraform Run workflow
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  deploy_in_useast1:
    name: Deploy to us-east-1 Region
    runs-on: ubuntu-latest
    strategy:
      matrix:
        approved:
          - true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Authorization to AWS Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -var-file=useast1.tfvars

  deploy_in_useast2:
    name: Deploy to us-east-2 Region
    runs-on: ubuntu-latest
    needs: deploy_in_useast1
    strategy:
      matrix:
        approved:
          - true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Authorization to AWS Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -var-file=useast2.tfvars

  approve_to_deploy:
    name: Approval Step
    runs-on: ubuntu-latest
    needs:
      - deploy_in_useast1
      - deploy_in_useast2
    if: always()
    steps:
      - name: Request Approval
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
